services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: news_feed_bot
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/
  
  goose:
    image: golang:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["goose"]
    depends_on:
      - db

volumes:
  db: